# Generated by Django 5.2.6 on 2025-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='amount_goal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
