# Generated by Django 5.2.6 on 2025-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_projects_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='about_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='days_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='donors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
