# Generated by Django 5.2.6 on 2025-09-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_projects_about_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='amount_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
