# Generated by Django 5.2.6 on 2025-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, default='img/staticimg.jpg', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
