# Generated by Django 5.2.6 on 2025-09-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
