# Generated by Django 5.2.6 on 2025-09-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.ImageField(default=1, upload_to='profiles/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
